version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: staff_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: staff_management
    ports:
      - "5002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: staff_backend
    depends_on:
      - postgres
    ports:
      - "3002:3002"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: admin123
      DB_NAME: staff_management
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: staff_frontend
    volumes:
      - ./HR-Staffmanagement:/usr/share/nginx/html:ro
    ports:
      - "7005:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

